name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .node-version

      - name: Use .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Install (npm)
        run: npm ci

      - name: Install (dotnet tool)
        run: dotnet tool restore

      - name: CI build
        run: npm run ci-build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: coverage
          fail_ci_if_error: true
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true # to debug
